/**
 * This file is auto-generated by nestjs-proto-gen-ts
 */

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export interface UserService {
  findOneById(
    data: UserByIdRequest,
    metadata?: Metadata,
    ...rest: any[]
  ): Observable<UserDto>;
}

export interface UserByIdRequest {
  id: string;
}

export interface UserDto {
  id: string;
  name: string;
}
